stages:
  - build
  - test
  - deploy

maven-build:
  stage: build
  environment: staging
  script:
    - "mvn -DskipTests clean compile"

maven-test:
  stage: test
  environment: staging
  script:
    - "mvn test"

maven-deploy:
  stage: deploy
  environment: staging
  script:
    - "mvn deploy -DskipTests -DperformRelease"
  only:
    - /^master$/
    - /^dev$/
    - /^ft-.*-deploy$/
    - /^rl-.*$/
    - /^hf-.*$/
